global:
  scrape_interval:     60s # Set the scrape interval to every 60 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 60 seconds. Default is every 1 minute.

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093'] # Default Alertmanager port

# Load rules once and periodically evaluate them against the currently ingested data.
rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'api-monitor'
    static_configs:
      - targets: ['localhost:8000']
